#!/bin/bash

export NODE_TLS_REJECT_UNAUTHORIZED=0;
cd $FIELDDB_HOME/FieldDBWebServer
forever \
start \
-al $FIELDDB_HOME/logs/fielddbwww.log \
-ao $FIELDDB_HOME/logs/fielddbwwwout.log \
-ae $FIELDDB_HOME/logs/fielddbwwwerr.log \
bin/fielddb-web-server
